language: scala
script: "sbt clean coverage test"
after_script:
    - sbt coveralls > /dev/null 2>&1
scala:
    - "2.11.7"
jdk:
    - oraclejdk8
    - openjdk8
env:
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
branches:
  only:
    - master
